baseURL = 'https://GuilHartt.github.io/sorting-chaos/'
locale = 'pt-br'
title = 'Ordenando o Caos'
theme = 'folio'

[params]
  [params.author]
    name = "Guilherme Avelar"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  [markup.highlight]
    style = "catppuccin-latte"
